FROM mybaseimage AS first-stage
RUN touch firstfile
RUN touch secondfile
RUN touch thirdfile

FROM first-stage AS second-stage
RUN echo "Hello Inc0"
RUN echo "Hello Inc1"
RUN echo "Hello Inc2"
RUN echo "Hello Inc3"

FROM second-stage AS third-stage
RUN echo "Before, firstfile content:" && cat firstfile
RUN echo "[$(date)] Test Inc" >> firstfile
RUN echo "[$(date)] Test Inc" >> secondfile
RUN echo "Current, firstfile content:" && cat firstfile
