#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build OpenWrt

on:
  release:
    types: [published]
  repository_dispatch:
  push:
    paths-ignore:
    - README.md
    - LICENSE
    - .dockerignore

#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]

env:
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
  USERNAME: ${{secrets.docker_username}}
  PASSWORD: ${{secrets.docker_password}}

jobs:
  docker-build:
    runs-on: ubuntu-18.04
    if: github.event_name == 'release' || (github.event_name == 'repository_dispatch' && github.event.action == 'docker')
    env:
      IMAGE_NAME: ${{secrets.docker_username}}/openwrt_x86_64
      IMAGE_TAG: latest
      BUILDX_DRIVER: docker-container
      CONTEXT: .
      DOCKERFILE: Dockerfile
      REPO_URL: https://github.com/coolsnowwolf/lede
      REPO_BRANCH: master
      CONFIG_FILE: 'config.diff'
      BUILD_ARGS: 'REPO_URL REPO_BRANCH CONFIG_FILE'

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Init and configure docker
      run: |
        scripts/cleanup.sh
        . docker.sh
        configure_docker
        login_to_registry

    - name: Initialize environment
      run: |
        . docker.sh
        build_image init-env
        echo "::set-env name=LAST_BUILD_STAGE::init-env"

    - name: Clone all source code
      run: |
        . docker.sh
        build_image clone
        echo "::set-env name=LAST_BUILD_STAGE::clone"

    # Allow intermediate customization
    - name: SSH connection to Actions
      if: github.event_name == 'repository_dispatch' && github.event.client_payload.debug == true
      env:
        TIMEOUT_MIN: 5
      uses: tete1030/debugger-action@my

    - name: Load custom configuration
      run: |
        . docker.sh
        build_image custom
        echo "::set-env name=LAST_BUILD_STAGE::custom"

    - name: Download package
      run: |
        . docker.sh
        build_image download
        echo "::set-env name=LAST_BUILD_STAGE::download"

    - name: Print disk space size
      run: df -h

    - name: Multi-thread compile
      id: mtcompile
      continue-on-error: true
      env:
        OUTPUT: type=docker
      run: |
        echo "::set-output name=started::yes"
        . docker.sh
        build_image mcompile
        echo "::set-env name=LAST_BUILD_STAGE::mcompile"
        echo "::set-output name=success::yes"

        # switch building mode
        echo "::set-env name=NO_PUSH::1"
        echo "::set-env name=BUILDX_DRIVER::docker"
        export BUILDX_DRIVER=docker
        reconfigure_docker_buildx


    # previous failure will cause current job failure
    - name: Single-thread compile
      if: steps.mtcompile.outputs.started == 'yes' && steps.mtcompile.outputs.success != 'yes'
      env:
        OUTPUT: type=docker
      run: |
        . docker.sh
        build_image scompile
        echo "::set-env name=LAST_BUILD_STAGE::scompile"

        # switch building mode
        echo "::set-env name=NO_PUSH::1"
        echo "::set-env name=BUILDX_DRIVER::docker"
        export BUILDX_DRIVER=docker
        reconfigure_docker_buildx

    - name: Print disk space size
      run: df -h

    - name: Push image and cache
      if: (!cancelled()) && (!failure() || github.event_name == 'repository_dispatch' && github.event.client_payload.push_when_fail == true)
      run: |
        . docker.sh
        push_image_and_cache

    - name: Copy out bin directory
      id: copydir
      if: (!cancelled())
      run: |
        . docker.sh
        if [ ! -d "$(pwd)/openwrt" ]; then
          mkdir "$(pwd)/openwrt"
        fi
        copy_files /home/builder/openwrt/bin "$(pwd)/openwrt/bin"
        echo "::set-output name=status::success"

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_bin
        path: openwrt/bin

    - name: Organize files
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"

    - name: Upload firmware
      uses: actions/upload-artifact@master
      if: steps.copydir.outputs.status == 'success' && success() && !cancelled()
      with:
        name: OpenWrt_firmware
        path: ${{ env.FIRMWARE }}

    # failure checking
    - name: SSH connection to Actions
      if: failure() || (github.event_name == 'repository_dispatch' && github.event.client_payload.debug == true)
      uses: tete1030/debugger-action@my

  docker-build-inc:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' || (github.event_name == 'repository_dispatch' && github.event.action == 'docker-inc')
    env:
      IMAGE_BASE: ${{secrets.docker_username}}/openwrt_x86_64:latest-inc
      IMAGE_NAME: ${{secrets.docker_username}}/openwrt_x86_64
      IMAGE_TAG: latest-inc
      CONTEXT: .
      BUILDX_DRIVER: docker
      DOCKERFILE: Dockerfile-inc
      REPO_URL: https://github.com/coolsnowwolf/lede
      REPO_BRANCH: master
      CONFIG_FILE: 'config.diff'
      NO_REMOTE_CACHE: 1
      NO_PUSH: 1
      BUILD_ARGS: 'CONFIG_FILE IMAGE_BASE UPDATE_REPO UPDATE_FEEDS'

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Init and configure docker
      run: |
        UPDATE_FEEDS=0
        [ "x${{ github.event.client_payload.update_feeds }}" != "xtrue" ] || UPDATE_FEEDS=1
        echo "::set-env name=UPDATE_FEEDS::${UPDATE_FEEDS}"
        UPDATE_REPO=0
        [ "x${{ github.event.client_payload.update_repo }}" != "xtrue" ] || UPDATE_REPO=1
        echo "::set-env name=UPDATE_REPO::${UPDATE_REPO}"
        
        scripts/cleanup.sh
        . docker.sh
        configure_docker
        login_to_registry

    - name: Use latest base image
      if: github.event_name == 'repository_dispatch' && github.event.client_payload.use_latest == true
      run: |
        . docker.sh
        create_tag_alias ${IMAGE_NAME}:latest ${IMAGE_BASE}

    - name: Pull base image
      run: |
        . docker.sh
        pull_image

    # Allow intermediate customization
    - name: SSH connection to Actions
      if: github.event_name == 'repository_dispatch' && github.event.client_payload.debug == true
      env:
        TIMEOUT_MIN: 5
      uses: tete1030/debugger-action@my

    - name: Update repo and packages
      run: |
        . docker.sh
        build_image updateclone
        echo "::set-env name=LAST_BUILD_STAGE::updateclone"

    - name: Apply customizations
      run: |
        . docker.sh
        build_image custom
        echo "::set-env name=LAST_BUILD_STAGE::custom"

    - name: Download package
      run: |
        . docker.sh
        build_image download
        echo "::set-env name=LAST_BUILD_STAGE::download"

    - name: Print disk space size
      run: df -h

    - name: Multi-thread compile
      id: mtcompile
      continue-on-error: true
      env:
        USE_DOCKER_BUILD: 1
        SQUASH: 1
      run: |
        echo "::set-output name=started::yes"
        . docker.sh
        build_image mcompile
        echo "::set-env name=LAST_BUILD_STAGE::mcompile"
        echo "::set-output name=success::yes"

    # previous failure will cause current job failure
    - name: Single-thread compile
      if: steps.mtcompile.outputs.started == 'yes' && steps.mtcompile.outputs.success != 'yes'
      env:
        USE_DOCKER_BUILD: 1
        SQUASH: 1
      run: |
        . docker.sh
        build_image scompile
        echo "::set-env name=LAST_BUILD_STAGE::scompile"

    - name: Print disk space size
      run: df -h

    - name: Push image
      if: (!cancelled()) && (!failure() || github.event_name == 'repository_dispatch' && github.event.client_payload.push_when_fail == true)
      run: |
        . docker.sh
        push_image

    - name: Copy out bin directory
      id: copydir
      if: (!cancelled())
      run: |
        . docker.sh
        if [ ! -d "$(pwd)/openwrt" ]; then
          mkdir "$(pwd)/openwrt"
        fi
        copy_files /home/builder/openwrt/bin "$(pwd)/openwrt/bin"
        echo "::set-output name=status::success"

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_bin
        path: openwrt/bin

    - name: Organize files
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"
  
    - name: Upload firmware
      uses: actions/upload-artifact@master
      if: steps.copydir.outputs.status == 'success' && success() && !cancelled()
      with:
        name: OpenWrt_firmware
        path: ${{ env.FIRMWARE }}

    # failure checking
    - name: SSH connection to Actions
      if: failure() || (github.event_name == 'repository_dispatch' && github.event.client_payload.debug == true)
      uses: tete1030/debugger-action@my

  docker-build-package:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' || (github.event_name == 'repository_dispatch' && github.event.action == 'docker-package')
    env:
      IMAGE_BASE: ${{secrets.docker_username}}/openwrt_x86_64:latest-package
      IMAGE_NAME: ${{secrets.docker_username}}/openwrt_x86_64
      IMAGE_TAG: latest-package
      CONTEXT: .
      BUILDX_DRIVER: docker
      DOCKERFILE: Dockerfile-package
      REPO_URL: https://github.com/coolsnowwolf/lede
      REPO_BRANCH: master
      CONFIG_FILE: 'config.diff'
      NO_REMOTE_CACHE: 1
      NO_PUSH: 1
      BUILD_ARGS: 'CONFIG_FILE IMAGE_BASE UPDATE_FEEDS'

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Init and configure docker
      run: |
        UPDATE_FEEDS=0
        [ "x${{ github.event.client_payload.update_feeds }}" != "xtrue" ] || UPDATE_FEEDS=1
        echo "::set-env name=UPDATE_FEEDS::${UPDATE_FEEDS}"
        scripts/cleanup.sh
        . docker.sh
        configure_docker
        login_to_registry
        touch .start_timestamp

    - name: Use latest base image
      if: github.event_name == 'repository_dispatch' && ( github.event.client_payload.use_latest == true || github.event.client_payload.use_latest_inc == true )
      env:
        BOOL_USE_LATEST: ${{ github.event.client_payload.use_latest }}
        BOOL_USE_LATEST_INC: ${{ github.event.client_payload.use_latest_inc }}
      run: |
        . docker.sh
        if [ "x${BOOL_USE_LATEST}" = "xtrue" ]; then
          test "x${BOOL_USE_LATEST_INC}" != "xtrue"
          create_tag_alias ${IMAGE_NAME}:latest ${IMAGE_BASE}
        else
          create_tag_alias ${IMAGE_NAME}:latest-inc ${IMAGE_BASE}
        fi

    - name: Pull base image
      run: |
        . docker.sh
        pull_image

    # Allow intermediate customization
    - name: SSH connection to Actions
      if: github.event_name == 'repository_dispatch' && github.event.client_payload.debug == true
      env:
        TIMEOUT_MIN: 5
      uses: tete1030/debugger-action@my

    - name: Update repo and packages
      run: |
        . docker.sh
        build_image updateclone
        echo "::set-env name=LAST_BUILD_STAGE::updateclone"

    - name: Apply customizations
      run: |
        . docker.sh
        build_image custom
        echo "::set-env name=LAST_BUILD_STAGE::custom"

    - name: Download package
      run: |
        . docker.sh
        build_image download
        echo "::set-env name=LAST_BUILD_STAGE::download"

    - name: Print disk space size
      run: df -h

    - name: Multi-thread compile
      id: mtcompile
      continue-on-error: true
      env:
        USE_DOCKER_BUILD: 1
        SQUASH: 1
      run: |
        echo "::set-output name=started::yes"
        . docker.sh
        build_image mcompile
        echo "::set-env name=LAST_BUILD_STAGE::mcompile"
        echo "::set-output name=success::yes"

    # previous failure will cause current job failure
    - name: Single-thread compile
      if: steps.mtcompile.outputs.started == 'yes' && steps.mtcompile.outputs.success != 'yes'
      env:
        USE_DOCKER_BUILD: 1
        SQUASH: 1
      run: |
        . docker.sh
        build_image scompile
        echo "::set-env name=LAST_BUILD_STAGE::scompile"

    - name: Print disk space size
      run: df -h

    - name: Push image
      if: (!cancelled()) && (!failure() || github.event_name == 'repository_dispatch' && github.event.client_payload.push_when_fail == true)
      run: |
        . docker.sh
        push_image

    - name: Copy out bin directory
      id: copydir
      if: (!cancelled())
      run: |
        . docker.sh
        if [ ! -d "$(pwd)/openwrt" ]; then
          mkdir "$(pwd)/openwrt"
        fi
        copy_files /home/builder/openwrt/bin "$(pwd)/openwrt/bin"
        echo "::set-output name=status::success"

    - name: Remove firmware
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      run: |
        shopt -s extglob
        cd openwrt/bin/targets/*/*
        all_extra_files=( !(packages) )
        rm -rf "${all_extra_files[@]}"

    - name: Upload packages
      uses: actions/upload-artifact@master
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_packages
        path: openwrt/bin

    - name: Remove old packages
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        find . -type f -not -newer ../../../../../.start_timestamp -exec rm -f {} \;

    - name: Upload new packages
      uses: actions/upload-artifact@master
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_new_packages
        path: openwrt/bin

    # failure checking
    - name: SSH connection to Actions
      if: failure() || (github.event_name == 'repository_dispatch' && github.event.client_payload.debug == true)
      uses: tete1030/debugger-action@my

  direct-build:
    runs-on: ubuntu-18.04
    if: github.event_name == 'repository_dispatch' && github.event.action == 'direct'
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialize environment
      run: |
        scripts/cleanup.sh
        scripts/initenv.sh

    - name: Clone all source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run:
        scripts/update_repo.sh
        UPDATE_FEEDS=1 scripts/update_feeds.sh

    - name: Load custom configuration
      env:
        CONFIG_FILE: 'config.diff'
      run: scripts/customize.sh

    # Allow intermediate customization
    - name: SSH connection to Actions
      if: github.event_name == 'repository_dispatch' && github.event.client_payload.debug == true
      env:
        TIMEOUT_MIN: 5
      uses: tete1030/debugger-action@my

    - name: Download package
      run: scripts/download.sh

    - name: Print disk space size
      run: df -h

    - name: Multi-thread compile
      id: mtcompile
      continue-on-error: true
      run: |
        echo "::set-output name=started::yes"
        scripts/compile.sh m
        echo "::set-output name=success::yes"

    # previous failure will cause current job failure
    - name: Single-thread compile
      if: steps.mtcompile.outputs.started == 'yes' && steps.mtcompile.outputs.success != 'yes'
      run: scripts/compile.sh s

    - name: Print disk space size
      run: df -h

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: (!cancelled())
      with:
        name: OpenWrt_bin
        path: openwrt/bin

    - name: Organize files
      if: (!cancelled())
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"

    - name: Upload firmware
      uses: actions/upload-artifact@master
      if: (success() && !cancelled())
      with:
        name: OpenWrt_firmware
        path: ${{ env.FIRMWARE }}

    # failure checking
    - name: SSH connection to Actions
      if: failure() || (github.event_name == 'repository_dispatch' && github.event.client_payload.debug == true)
      uses: tete1030/debugger-action@my

# Base
# * +mentohust
# * -shadowsocksr
# * -unblockmusic
# * -v2ray
# * -samba +samba4
# * -adbyby
# * -xlnetacc
# * -mia
# * -wifi_schedule
# * -kms
# * -zerotier
# * +dockerce
# * +curl
# * +wget

# Install
# * autossh
# * openclash
# * fping
# * netdata
# * zsh
# * tcpdump
# * dmesg
# * tmux
# * vim-full
# * strace
# * htop

# Change source
# * Upgrade download_pl
# * Add mentohust
# * autossh.init
# * transmission init.d
# * netdata init.d upgrade
# * netdata makefile upgrade for 1.19
# * Add libJudy for netdata
# * netdata add go.d.plugin
# * openclash replace clashr
# 
