#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build OpenWrt

on:
  release:
    types: [published]
  deployment:
  repository_dispatch:
  push:
    paths-ignore:
    - README.md
    - LICENSE
    - .dockerignore
  schedule:
    - cron: '*/5 * * * *'
  watch:
    types: [started]

env:
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
  DK_USERNAME: ${{secrets.docker_username}}
  DK_PASSWORD: ${{secrets.docker_password}}
  BUILDER_NAME: openwrt_x86_64
  BUILDER_TAG: latest
  DK_CONTEXT: .
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master

jobs:
  context:
    name: Print runner context (for debugging)
    runs-on: ubuntu-18.04
    steps:
    - name: Dump github context
      run: |
        cat << 'EOF'
        ${{toJSON(github)}}
        EOF

  docker-build:
    runs-on: ubuntu-18.04
    if: |
      github.event_name == 'release' || (
        github.event_name == 'repository_dispatch' && 
        github.event.action == 'docker-build'
      ) || (
        github.event_name == 'deployment' && 
        github.event.deployment.task == 'docker-build'
      )
    name: ${{matrix.title}}
    strategy:
      fail-fast: true
      matrix: 
        mode: [normal, test]
        include:
        - mode: normal
          title: docker-build
        - mode: test
          title: test-docker-build
    env:
      DK_BUILDX_DRIVER: docker-container
      DK_DOCKERFILE: Dockerfile
      CONFIG_FILE: 'config.diff'
      BUILD_ARGS: 'REPO_URL REPO_BRANCH CONFIG_FILE'

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Init test env
      if: matrix.mode == 'test'
      run: |
        echo "::set-env name=DK_DOCKERFILE::tests/${DK_DOCKERFILE}"
        echo "::set-env name=BUILDER_TAG::test-${BUILDER_TAG}"
        echo "::set-env name=TEST::1"

    - name: Init build env
      run: |
        echo "::set-env name=IMAGE_NAME::${DK_USERNAME}/${BUILDER_NAME}"
        echo "::set-env name=IMAGE_TAG::${BUILDER_TAG}"
        scripts/cleanup.sh

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Configure docker
      run: |
        . docker.sh
        configure_docker
        login_to_registry

    - name: Initialize environment
      run: |
        . docker.sh
        build_image init-env
        echo "::set-env name=STATE_LAST_BUILD_STAGE::init-env"

    - name: Clone all source code
      run: |
        . docker.sh
        build_image clone
        echo "::set-env name=STATE_LAST_BUILD_STAGE::clone"

    # Allow intermediate customization
    - name: SSH connection to Actions
      if: github.event.client_payload.debug == true || github.event.deployment.payload.debug == true
      env:
        TIMEOUT_MIN: 5
      uses: tete1030/debugger-action@my

    - name: Load custom configuration
      run: |
        . docker.sh
        build_image custom
        echo "::set-env name=STATE_LAST_BUILD_STAGE::custom"

    - name: Download package
      run: |
        . docker.sh
        build_image download
        echo "::set-env name=STATE_LAST_BUILD_STAGE::download"

    - name: Print disk space size
      run: df -h

    - name: Compile
      run: |
        . docker.sh
        build_image compile
        echo "::set-env name=STATE_LAST_BUILD_STAGE::compile"

    - name: Print disk space size
      run: df -h

    - name: Push image and cache
      if: |
        !cancelled() && (
          success() ||
          github.event.client_payload.push_when_fail == true ||
          github.event.deployment.payload.push_when_fail == true
        )
      run: |
        . docker.sh
        push_image_and_cache

    - name: Copy out bin directory
      id: copydir
      if: (!cancelled())
      run: |
        . docker.sh
        if [ ! -d "$(pwd)/openwrt" ]; then
          mkdir "$(pwd)/openwrt"
        fi
        copy_files /home/builder/openwrt/bin "$(pwd)/openwrt/bin"
        echo "::set-output name=status::success"

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_bin
        path: openwrt/bin

    - name: Organize files
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"

    - name: Upload firmware
      uses: actions/upload-artifact@master
      if: steps.copydir.outputs.status == 'success' && success() && !cancelled()
      with:
        name: OpenWrt_firmware
        path: ${{ env.FIRMWARE }}

    # failure checking
    - name: SSH connection to Actions
      if: |
        failure() ||
        github.event.client_payload.debug == true ||
        github.event.deployment.payload.debug == true
      uses: tete1030/debugger-action@my

  docker-build-inc:
    runs-on: ubuntu-18.04
    if: | 
      (
        github.event_name == 'repository_dispatch' && 
        github.event.action == 'docker-build-inc'
      ) || (
        github.event_name == 'deployment' && 
        github.event.deployment.task == 'docker-build-inc'
      )
    name: ${{matrix.title}}
    strategy:
      fail-fast: true
      matrix:
        mode: [normal, test]
        include:
        - mode: normal
          title: docker-build-inc
        - mode: test
          title: test-docker-build-inc
    env:
      DK_BUILDX_DRIVER: docker
      DK_DOCKERFILE: Dockerfile-inc
      CONFIG_FILE: 'config.diff'
      NO_REMOTE_CACHE: 1
      NO_BUILDTIME_PUSH: 1
      BUILD_ARGS: 'CONFIG_FILE IMAGE_BASE UPDATE_REPO UPDATE_FEEDS'

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Init test env
      if: matrix.mode == 'test'
      run: |
        echo "::set-env name=DK_DOCKERFILE::tests/${DK_DOCKERFILE}"
        echo "::set-env name=BUILDER_TAG::test-${BUILDER_TAG}"
        echo "::set-env name=TEST::1"

    - name: Init build env
      run: |
        # set-env command does not export env for current shell
        export IMAGE_NAME="${DK_USERNAME}/${BUILDER_NAME}"
        export IMAGE_TAG=${BUILDER_TAG}-inc
        echo "::set-env name=IMAGE_NAME::${IMAGE_NAME}"
        echo "::set-env name=IMAGE_TAG::${IMAGE_TAG}"
        echo "::set-env name=IMAGE_BASE::${DK_REGISTRY:+$DK_REGISTRY/}${IMAGE_NAME}:${IMAGE_TAG}"
        echo "::set-env name=IMAGE_LATEST::${DK_REGISTRY:+$DK_REGISTRY/}${IMAGE_NAME}:${BUILDER_TAG}"

        UPDATE_FEEDS=0
        [ "x${{ github.event.client_payload.update_feeds || github.event.deployment.payload.update_feeds }}" != "xtrue" ] || UPDATE_FEEDS=1
        echo "::set-env name=UPDATE_FEEDS::${UPDATE_FEEDS}"
        UPDATE_REPO=0
        [ "x${{ github.event.client_payload.update_repo || github.event.deployment.payload.update_repo }}" != "xtrue" ] || UPDATE_REPO=1
        echo "::set-env name=UPDATE_REPO::${UPDATE_REPO}"

        scripts/cleanup.sh

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Configure docker
      run: |
        . docker.sh
        configure_docker
        login_to_registry

    - name: Check if use latest base image
      env:
        BOOL_USE_LATEST: ${{ github.event.client_payload.use_latest || github.event.deployment.payload.use_latest }}
      run: |
        . docker.sh
        set +eo pipefail
        docker buildx imagetools inspect "${IMAGE_BASE}"
        ret_val=$?
        set -eo pipefail
        if [ "x${BOOL_USE_LATEST}" = "xtrue" -o "x${ret_val}" != "x0" ]; then
          echo "Creating '${IMAGE_BASE}' from '${IMAGE_LATEST}'"
          create_remote_tag_alias "${IMAGE_LATEST}" "${IMAGE_BASE}"
        fi

    - name: Pull base image
      run: |
        . docker.sh
        pull_image

    # Allow intermediate customization
    - name: SSH connection to Actions
      if: github.event.client_payload.debug == true || github.event.deployment.payload.debug == true
      env:
        TIMEOUT_MIN: 5
      uses: tete1030/debugger-action@my

    - name: Update repo and packages
      run: |
        . docker.sh
        build_image updateclone
        echo "::set-env name=STATE_LAST_BUILD_STAGE::updateclone"

    - name: Apply customizations
      run: |
        . docker.sh
        build_image custom
        echo "::set-env name=STATE_LAST_BUILD_STAGE::custom"

    - name: Download package
      run: |
        . docker.sh
        build_image download
        echo "::set-env name=STATE_LAST_BUILD_STAGE::download"

    - name: Print disk space size
      run: df -h

    - name: Compile
      run: |
        . docker.sh
        build_image compile
        echo "::set-env name=STATE_LAST_BUILD_STAGE::compile"

    - name: Print disk space size
      run: df -h

    - name: Push image
      if: |
        !cancelled() && (
          success() ||
          github.event.client_payload.push_when_fail == true ||
          github.event.deployment.payload.push_when_fail == true
        )
      run: |
        . docker.sh
        push_image

    - name: Copy out bin directory
      id: copydir
      if: (!cancelled())
      run: |
        . docker.sh
        if [ ! -d "$(pwd)/openwrt" ]; then
          mkdir "$(pwd)/openwrt"
        fi
        copy_files /home/builder/openwrt/bin "$(pwd)/openwrt/bin"
        echo "::set-output name=status::success"

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_bin
        path: openwrt/bin

    - name: Organize files
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"
  
    - name: Upload firmware
      uses: actions/upload-artifact@master
      if: steps.copydir.outputs.status == 'success' && success() && !cancelled()
      with:
        name: OpenWrt_firmware
        path: ${{ env.FIRMWARE }}

    # failure checking
    - name: SSH connection to Actions
      if: |
        failure() ||
        github.event.client_payload.debug == true ||
        github.event.deployment.payload.debug == true
      uses: tete1030/debugger-action@my

  docker-build-package:
    runs-on: ubuntu-18.04
    if: |
      github.event_name == 'push' || (
        github.event_name == 'repository_dispatch' && 
        github.event.action == 'docker-build-package'
      ) || (
        github.event_name == 'deployment' && 
        github.event.deployment.task == 'docker-build-package'
      )
    name: ${{matrix.title}}
    strategy:
      fail-fast: true
      matrix:
        mode: [normal, test]
        include:
        - mode: normal
          title: docker-build-package
        - mode: test
          title: test-docker-build-package
    env:
      DK_BUILDX_DRIVER: docker
      DK_DOCKERFILE: Dockerfile-package
      CONFIG_FILE: 'config.diff'
      NO_REMOTE_CACHE: 1
      NO_BUILDTIME_PUSH: 1
      BUILD_ARGS: 'CONFIG_FILE IMAGE_BASE UPDATE_FEEDS'

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Init test env
      if: matrix.mode == 'test'
      run: |
        echo "::set-env name=DK_DOCKERFILE::tests/${DK_DOCKERFILE}"
        echo "::set-env name=BUILDER_TAG::test-${BUILDER_TAG}"
        echo "::set-env name=TEST::1"

    - name: Init build env
      run: |
        # set-env command does not export env for current shell
        export IMAGE_NAME="${DK_USERNAME}/${BUILDER_NAME}"
        export IMAGE_TAG=${BUILDER_TAG}-package
        echo "::set-env name=IMAGE_NAME::${IMAGE_NAME}"
        echo "::set-env name=IMAGE_TAG::${IMAGE_TAG}"
        echo "::set-env name=IMAGE_BASE::${DK_REGISTRY:+$DK_REGISTRY/}${IMAGE_NAME}:${IMAGE_TAG}"
        echo "::set-env name=IMAGE_LATEST::${DK_REGISTRY:+$DK_REGISTRY/}${IMAGE_NAME}:${BUILDER_TAG}"
        echo "::set-env name=IMAGE_LATEST_INC::${DK_REGISTRY:+$DK_REGISTRY/}${IMAGE_NAME}:${BUILDER_TAG}-inc"

        UPDATE_FEEDS=0
        [ "x${{ github.event.client_payload.update_feeds || github.event.deployment.payload.update_feeds }}" != "xtrue" ] || UPDATE_FEEDS=1
        echo "::set-env name=UPDATE_FEEDS::${UPDATE_FEEDS}"

        scripts/cleanup.sh

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Configure docker
      run: |
        . docker.sh
        configure_docker
        login_to_registry
        touch .start_timestamp

    - name: Check if use latest base image
      env:
        BOOL_USE_LATEST: ${{ github.event.client_payload.use_latest || github.event.deployment.payload.use_latest }}
        BOOL_USE_LATEST_INC: ${{ github.event.client_payload.use_latest_inc || github.event.deployment.payload.use_latest_inc }}
      run: |
        . docker.sh
        set +eo pipefail
        docker buildx imagetools inspect "${IMAGE_BASE}"
        ret_val=$?
        set -eo pipefail
        if [ "x${BOOL_USE_LATEST}" = "xtrue" -o "x${BOOL_USE_LATEST_INC}" = "xtrue" -o "x${ret_val}" != "x0" ]; then
          IMAGE_SELECTED="${IMAGE_LATEST}"
          if [ "x${BOOL_USE_LATEST_INC}" = "xtrue" ]; then
            if [ "x${BOOL_USE_LATEST}" = "xtrue" ]; then
              echo "You cannot use both 'use_latest' and 'use_latest_inc'" >&2
              exit 1
            fi
            IMAGE_SELECTED="${IMAGE_LATEST_INC}"
          fi
          echo "Creating '${IMAGE_BASE}' from '${IMAGE_SELECTED}'"
          create_remote_tag_alias "${IMAGE_SELECTED}" "${IMAGE_BASE}"
        fi

    - name: Pull base image
      run: |
        . docker.sh
        pull_image

    # Allow intermediate customization
    - name: SSH connection to Actions
      if: github.event.client_payload.debug == true || github.event.deployment.payload.debug == true
      env:
        TIMEOUT_MIN: 5
      uses: tete1030/debugger-action@my

    - name: Update repo and packages
      run: |
        . docker.sh
        build_image updateclone
        echo "::set-env name=STATE_LAST_BUILD_STAGE::updateclone"

    - name: Apply customizations
      run: |
        . docker.sh
        build_image custom
        echo "::set-env name=STATE_LAST_BUILD_STAGE::custom"

    - name: Download package
      run: |
        . docker.sh
        build_image download
        echo "::set-env name=STATE_LAST_BUILD_STAGE::download"

    - name: Print disk space size
      run: df -h

    - name: Compile
      run: |
        . docker.sh
        build_image compile
        echo "::set-env name=STATE_LAST_BUILD_STAGE::compile"

    - name: Print disk space size
      run: df -h

    - name: Push image
      if: (!cancelled()) && (success() || github.event.client_payload.push_when_fail == true || github.event.deployment.payload.push_when_fail == true)
      run: |
        . docker.sh
        push_image

    - name: Copy out bin directory
      id: copydir
      if: (!cancelled())
      run: |
        . docker.sh
        if [ ! -d "$(pwd)/openwrt" ]; then
          mkdir "$(pwd)/openwrt"
        fi
        copy_files /home/builder/openwrt/bin "$(pwd)/openwrt/bin"
        echo "::set-output name=status::success"

    - name: Remove firmware
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      run: |
        shopt -s extglob
        cd openwrt/bin/targets/*/*
        all_extra_files=( !(packages) )
        rm -rf "${all_extra_files[@]}"

    - name: Upload packages
      uses: actions/upload-artifact@master
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_packages
        path: openwrt/bin

    - name: Remove old packages
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        find . -type f -not -newer ../../../../../.start_timestamp -exec rm -f {} \;

    - name: Upload new packages
      uses: actions/upload-artifact@master
      if: steps.copydir.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_new_packages
        path: openwrt/bin

    # failure checking
    - name: SSH connection to Actions
      if: failure() || github.event.client_payload.debug == true || github.event.deployment.payload.debug == true
      uses: tete1030/debugger-action@my

  direct-build:
    runs-on: ubuntu-18.04
    if: (
        github.event_name == 'repository_dispatch' &&
        github.event.action == 'direct-build'
      ) || (
        github.event_name == 'deployment' &&
        github.event.deployment.task == 'direct-build'
      )
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialize environment
      run: |
        scripts/cleanup.sh
        scripts/initenv.sh

    - name: Clone all source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run:
        scripts/update_repo.sh
        UPDATE_FEEDS=1 scripts/update_feeds.sh

    - name: Load custom configuration
      env:
        CONFIG_FILE: 'config.diff'
      run: scripts/customize.sh

    # Allow intermediate customization
    - name: SSH connection to Actions
      if: github.event.client_payload.debug == true || github.event.deployment.payload.debug == true
      env:
        TIMEOUT_MIN: 5
      uses: tete1030/debugger-action@my

    - name: Download package
      run: scripts/download.sh

    - name: Print disk space size
      run: df -h

    - name: Multi-thread compile
      id: mtcompile
      continue-on-error: true
      run: |
        echo "::set-output name=started::yes"
        scripts/compile.sh m
        echo "::set-output name=success::yes"

    # previous failure will cause current job failure
    - name: Single-thread compile
      if: steps.mtcompile.outputs.started == 'yes' && steps.mtcompile.outputs.success != 'yes'
      run: scripts/compile.sh s

    - name: Print disk space size
      run: df -h

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: (!cancelled())
      with:
        name: OpenWrt_bin
        path: openwrt/bin

    - name: Organize files
      if: (!cancelled())
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"

    - name: Upload firmware
      uses: actions/upload-artifact@master
      if: (success() && !cancelled())
      with:
        name: OpenWrt_firmware
        path: ${{ env.FIRMWARE }}

    # failure checking
    - name: SSH connection to Actions
      if: failure() || github.event.client_payload.debug == true || github.event.deployment.payload.debug == true
      uses: tete1030/debugger-action@my

# Base
# * +mentohust
# * -shadowsocksr
# * -unblockmusic
# * -v2ray
# * -samba +samba4
# * -adbyby
# * -xlnetacc
# * -mia
# * -wifi_schedule
# * -kms
# * -zerotier
# * +dockerce
# * +curl
# * +wget

# Install
# * autossh
# * openclash
# * fping
# * netdata
# * zsh
# * tcpdump
# * dmesg
# * tmux
# * vim-full
# * strace
# * htop

# Change source
# * Upgrade download_pl
# * Add mentohust
# * autossh.init
# * transmission init.d
# * netdata init.d upgrade
# * netdata makefile upgrade for 1.19
# * Add libJudy for netdata
# * netdata add go.d.plugin
# * openclash replace clashr
# 
